# Generated by Django 6.0 on 2025-12-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',), 'verbose_name': ('Проект',), 'verbose_name_plural': ('Проекты',)},
        ),
    ]
