# Generated by Django 6.0 on 2025-12-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': ('Проект',), 'verbose_name_plural': ('Проекты',)},
        ),
    ]
